version: '3.8'
services:
  database:
    image: postgres:15
    container_name: starpick-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: starpick
    ports:
      - "5432:5432"
